# Vertelt Netlify CMS hoe het met je GitHub repo moet praten
backend:
  name: git-gateway
  branch: main # Gebruik 'main' of 'master', afhankelijk van je repo

# Waar geüploade foto's worden opgeslagen
media_folder: "src/assets/images/uploads"
# Hoe de website de foto's moet benaderen
public_folder: "/assets/images/uploads"

# Definieer de content types
collections:
  - name: "leden" # De technische naam
    label: "Leden" # De naam in het CMS-menu
    folder: "src/leden" # CRUCIAAL: Hier worden de .md-bestanden opgeslagen
    create: true # Sta toe dat nieuwe leden worden aangemaakt
    slug: "{{naam}}" # Maakt bestandsnaam van de naam (bv. 'Twan Meurs' -> 'twan-meurs.md')
    fields: # De invulvelden voor elk lid
      - {label: "Volgorde (lager = hoger op de pagina)", name: "volgorde", widget: "number", default: 100}
      - {label: "Naam", name: "naam", widget: "string"}
      - {label: "Functie", name: "functie", widget: "string"}
      - {label: "Foto", name: "foto", widget: "image"}
      - {label: "Instagram URL (optioneel)", name: "instagram", widget: "string", required: false}
      - {label: "LinkedIn URL (optioneel)", name: "linkedin", widget: "string", required: false}
      - {label: "Bio", name: "body", widget: "markdown"}

       # VERVANG DE OUDE VERGADERINGEN COLLECTIE MET DIT
  - name: "paginas" # Een algemene collectie voor losse pagina's
    label: "Pagina's"
    files:
      # We beheren het rooster nu als één enkel bestand
      - file: "src/_data/rooster.json" # De data wordt opgeslagen in een JSON-bestand
        label: "Vergaderrooster"
        name: "rooster"
        fields:
          - {label: "Vaste Titel Vergadering", name: "vaste_titel", widget: "string", default: "Grote vergadering"}
          - {label: "Vaste Locatie", name: "vaste_locatie", widget: "string", default: "Gemeentehuis Wageningen"}
          - label: "Vergaderdata"
            name: "datums"
            widget: "list" # Dit maakt een herhaalbare lijst
            fields:
              - {label: "Datum", name: "datum", widget: "date", format: "DD-MM-YYYY"}
              - {label: "Notulist / Opening", name: "notulist", widget: "string", default: "TBA"}