# Vertelt Netlify CMS hoe het met je GitHub repo moet praten
backend:
  name: git-gateway
  branch: main # Gebruik 'main' of 'master', afhankelijk van je repo

# Waar geüploade foto's worden opgeslagen
media_folder: "src/assets/images/uploads"
# Hoe de website de foto's moet benaderen
public_folder: "/assets/images/uploads"

# Definieer de content types
collections:
  - name: "leden" # De technische naam
    label: "Leden" # De naam in het CMS-menu
    folder: "src/leden" # CRUCIAAL: Hier worden de .md-bestanden opgeslagen
    create: true # Sta toe dat nieuwe leden worden aangemaakt
    slug: "{{naam}}" # Maakt bestandsnaam van de naam (bv. 'Twan Meurs' -> 'twan-meurs.md')
    fields: # De invulvelden voor elk lid
      - {label: "Naam", name: "naam", widget: "string"}
      - {label: "Functie", name: "functie", widget: "string"}
      - {label: "Foto", name: "foto", widget: "image"}
      - {label: "Instagram URL (optioneel)", name: "instagram", widget: "string", required: false}
      - {label: "LinkedIn URL (optioneel)", name: "linkedin", widget: "string", required: false}
      - {label: "Bio", name: "body", widget: "markdown"}