# admin/config.yml

backend:
  name: git-gateway
  branch: main # Of 'master', afhankelijk van je standaard branch in GitHub

# Locatie voor media (zoals profielfoto's)
media_folder: "assets/uploads" 
public_folder: "/assets/uploads"

# Dit definieert de content types die je kunt beheren. We maken er één: Leden.
collections:
  - name: "leden"
    label: "Leden"
    folder: "src/leden" # We slaan nu elk lid op als een apart .md bestand
    create: true
    slug: "{{naam}}" # De bestandsnaam wordt de naam van het lid
    fields:
      - {label: "Naam", name: "naam", widget: "string"}
      - {label: "Functie", name: "functie", widget: "string"}
      - {label: "Foto", name: "foto", widget: "image"}
      - {label: "Bio", name: "body", widget: "markdown"}
      - {label: "Instagram URL", name: "instagram", widget: "string", required: false}
      - {label: "LinkedIn URL", name: "linkedin", widget: "string", required: false}